### ISSUE TITLE
[FEATURE] Docker-Compose script with resources

### ISSUE THREAD

**Issue by alexeyegorov** [cluster-apps-on-docker/spark-standalone-cluster-on-docker#40]
### Description

As I was trying out the 3.0.0 spark version and wanted to initialize workers with 2G or more, it failed every time. After looking up the [docker-compose wiki](https://docs.docker.com/compose/compose-file/), I've found that it is restricted by 2G as default and can be set in the docker-compose file. I would suggest to add these couple of lines for better understanding and setup of the local docker Spark cluster.

Here an example:

```
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
```
